# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-23 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird_hit_form',
            name='air_operator',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
