# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-23 16:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_bird_hit_form_air_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird_hit_form',
            name='ATC_inform',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'No')], default='Null', max_length=5),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='ATC_mark',
            field=models.CharField(default='n', max_length=1),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='DGCA_mark',
            field=models.CharField(default='n', max_length=1),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='aerod_depart',
            field=models.CharField(default='NUll', max_length=100),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='aerod_intend_arr',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='aerod_occ',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='air_reg',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='air_type_series',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='aircraft_tos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='altitude_AGL',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='bird_remains',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Null', max_length=5),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='bird_seen',
            field=models.CharField(choices=[('1', '1'), ('2-10', '2-10'), ('11-100', '11-100'), ('100+', '100+')], default='Null', max_length=10),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='bird_size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Null', max_length=10),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='bird_struck',
            field=models.CharField(choices=[('1', '1'), ('2-10', '2-10'), ('11-100', '11-100'), ('100+', '100+')], default='Null', max_length=10),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='damage_others',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='damage_parts',
            field=models.CharField(default='Null', max_length=500),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='date_of_occ',
            field=models.DateField(default=datetime.date(2018, 6, 23), verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='duration_time',
            field=models.CharField(choices=[('Dawn', 'Dawn'), ('Day', 'Day'), ('Dusk', 'Dusk'), ('Night', 'Night')], default='NULL', max_length=10),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='effect_on_flight',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='effect_others',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='engine_model',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='est_cost_of_repair',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='est_other',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='flight_no',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='operation_department',
            field=models.CharField(default='n', max_length=1),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='other_report_raised',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='other_reports',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='phase_of_flight',
            field=models.CharField(choices=[('Taxi', 'Taxi'), ('Take-off run', 'Take-off run'), ('Climb', 'Climb'), ('En-route', 'En-route'), ('Descend', 'Descend'), ('Approach', 'Approach'), ('Landing roll', 'Landing roll'), ('Ground Checks', 'Ground Checks')], default='Null', max_length=20),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='pilot_warned',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Null', max_length=10),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='position',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='precipitation',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='remarks',
            field=models.CharField(default='Null', max_length=1000),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='runway_in_use',
            field=models.CharField(default='Null', max_length=10),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='sky_condition',
            field=models.CharField(choices=[('No cloud', 'No cloud'), ('Some cloud', 'Some cloud'), ('Over cloud', 'Over cloud')], default='Null', max_length=10),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='speed',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='struck_others',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='struck_parts',
            field=models.CharField(default='Null', max_length=500),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='time_of_occ',
            field=models.TimeField(default=datetime.datetime(2018, 6, 23, 16, 18, 37, 885982), verbose_name='time published'),
        ),
        migrations.AddField(
            model_name='bird_hit_form',
            name='wildlife_desc',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
