# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-23 16:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_auto_20180623_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird_hit_form',
            name='submitted_by',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='bird_hit_form',
            name='time_of_occ',
            field=models.TimeField(default=datetime.datetime(2018, 6, 23, 16, 19, 27, 555611), verbose_name='time published'),
        ),
    ]
