# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-23 16:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_auto_20180623_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird_hit_form',
            name='time_of_occ',
            field=models.TimeField(default=datetime.datetime(2018, 6, 23, 16, 23, 22, 332767), verbose_name='time published'),
        ),
    ]
