# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-23 19:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0005_auto_20180623_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='incident_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(default=datetime.datetime(2018, 6, 23, 19, 32, 58, 46516, tzinfo=utc))),
                ('submitted_by', models.CharField(default='Null', max_length=100)),
                ('aircraft_identification', models.CharField(default='Null', max_length=1000)),
                ('type_of_incident', models.CharField(choices=[('AirProx', 'AirProx'), ('Obstruction on Runway', 'Obstruction on Runway'), ('Runway Incursion', 'Runway Incursion'), ('Procedure', 'Procedure'), ('Facility', 'Facility')], default='Null', max_length=20)),
                ('date_of_incident', models.DateField(default=datetime.date(2018, 6, 23), verbose_name='date published')),
                ('time_of_incident', models.TimeField(default=datetime.datetime(2018, 6, 23, 19, 32, 58, 46646), verbose_name='time published')),
                ('pos', models.CharField(default='Null', max_length=100)),
                ('head_and_route', models.CharField(default='Null', max_length=100)),
                ('true_airspeed', models.IntegerField(default=0, max_length=10)),
                ('speed_measured', models.CharField(choices=[('kt', 'kt'), ('km/h', 'km/h')], default='Null', max_length=20)),
                ('air_climb', models.CharField(choices=[('Level flight', 'Level flight'), ('climbing', 'climbing'), ('Descending', 'Descending')], default='Null', max_length=20)),
                ('air_bank', models.CharField(choices=[('wings level', 'wings level'), ('slight bank', 'slight bank'), ('moderate bank', 'moderate bank'), ('steep bank', 'steep bank'), ('inverted', 'inverted'), ('unknown', 'unknown')], default='Null', max_length=20)),
                ('air_dir', models.CharField(choices=[('left', 'left'), ('right', 'right'), ('unknown', 'unknown')], default='Null', max_length=20)),
                ('restr_visib', models.CharField(default='Null', max_length=500)),
                ('air_light', models.CharField(default='Null', max_length=500)),
                ('traffic_advice', models.CharField(choices=[('yes, based on radar', 'yes, based on radar'), ('yes, based on visual sighting', 'yes, based on visual sighting'), ('yes, based on other information', 'yes, based on other information'), ('no', 'no')], default='Null', max_length=50)),
                ('traffic_info', models.CharField(choices=[('yes, based on radar', 'yes, based on radar'), ('yes, based on visual sighting', 'yes, based on visual sighting'), ('yes, based on other information', 'yes, based on other information'), ('no', 'no')], default='Null', max_length=50)),
                ('ACAS', models.CharField(choices=[('Not Carried', 'Not Carried'), ('Type', 'Type'), ('Traffic advisory issued', 'Traffic advisory issued'), ('Resolution advisory issued', 'Resolution advisory issued'), ('Traffic or resolution advisory not issued ', 'Traffic or resolution advisory not issued ')], default='Null', max_length=50)),
                ('other_aircraft', models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('wrong aircraft sighted', 'wrong aircraft sighted')], default='Null', max_length=50)),
                ('avoid_action', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='Null', max_length=50)),
                ('type_of_flight_plan', models.CharField(choices=[('IFR', 'IFR'), ('VFR', 'VFR'), ('none', 'none')], default='Null', max_length=20)),
                ('type_and_call_sign', models.CharField(default='Null', max_length=100)),
                ('other_available_details', models.CharField(default='Null', max_length=500)),
                ('aircraft_reg', models.CharField(default='Null', max_length=150)),
                ('aircraft_type', models.CharField(default='Null', max_length=150)),
                ('operator', models.CharField(default='Null', max_length=150)),
                ('aero_depart', models.CharField(default='Null', max_length=150)),
                ('aero_first_landing', models.CharField(default='Null', max_length=150)),
                ('destination', models.CharField(default='Null', max_length=150)),
                ('operation_department', models.CharField(default='n', max_length=1)),
                ('ATC_mark', models.CharField(default='n', max_length=1)),
                ('DGCA_mark', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='bird_hit_form',
            name='time_of_occ',
            field=models.TimeField(default=datetime.datetime(2018, 6, 23, 19, 32, 58, 44945), verbose_name='time published'),
        ),
        migrations.AlterField(
            model_name='bird_hit_form',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 23, 19, 32, 58, 44593, tzinfo=utc)),
        ),
    ]
