# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-24 05:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0015_auto_20180624_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird_hit_form',
            name='time_of_occ',
            field=models.TimeField(default=datetime.datetime(2018, 6, 24, 5, 44, 4, 935096), verbose_name='time published'),
        ),
        migrations.AlterField(
            model_name='bird_hit_form',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 24, 5, 44, 4, 934543, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='incident_form',
            name='time_of_incident',
            field=models.TimeField(default=datetime.datetime(2018, 6, 24, 5, 44, 4, 938146), verbose_name='time published'),
        ),
        migrations.AlterField(
            model_name='incident_form',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 24, 5, 44, 4, 937941, tzinfo=utc)),
        ),
    ]
