# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-24 07:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0016_auto_20180624_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident_form',
            name='radar',
            field=models.CharField(choices=[('No radar available', 'No radar available'), ('Radar identification', 'Radar identification'), ('No radar identification', 'No radar identification')], default='Null', max_length=50),
        ),
        migrations.AlterField(
            model_name='bird_hit_form',
            name='time_of_occ',
            field=models.TimeField(default=datetime.datetime(2018, 6, 24, 7, 37, 40, 10408), verbose_name='time published'),
        ),
        migrations.AlterField(
            model_name='bird_hit_form',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 24, 7, 37, 40, 10034, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='incident_form',
            name='time_of_incident',
            field=models.TimeField(default=datetime.datetime(2018, 6, 24, 7, 37, 40, 12016), verbose_name='time published'),
        ),
        migrations.AlterField(
            model_name='incident_form',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 24, 7, 37, 40, 11892, tzinfo=utc)),
        ),
    ]
